// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSxg71d7IVb_U4QYIKCE-kccCVMUZEFow',
    appId: '1:1023542976787:web:0985ab855d2986ae02fae6',
    messagingSenderId: '1023542976787',
    projectId: 'react-noti-app-5c9f4',
    authDomain: 'react-noti-app-5c9f4.firebaseapp.com',
    storageBucket: 'react-noti-app-5c9f4.appspot.com',
    measurementId: 'G-P6ZG0Q4ZJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxFxPA0xXwByZ0LCypXd2Q9zQ92Q4v51M',
    appId: '1:1023542976787:android:01cc456fe2f5f19502fae6',
    messagingSenderId: '1023542976787',
    projectId: 'react-noti-app-5c9f4',
    storageBucket: 'react-noti-app-5c9f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmiUxdz4ExDRoGoYT1kuZLgoEdPQ-evk8',
    appId: '1:1023542976787:ios:a00ccfc16b744cb702fae6',
    messagingSenderId: '1023542976787',
    projectId: 'react-noti-app-5c9f4',
    storageBucket: 'react-noti-app-5c9f4.appspot.com',
    iosBundleId: 'com.example.wayoChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmiUxdz4ExDRoGoYT1kuZLgoEdPQ-evk8',
    appId: '1:1023542976787:ios:357ae4f2a817bf9102fae6',
    messagingSenderId: '1023542976787',
    projectId: 'react-noti-app-5c9f4',
    storageBucket: 'react-noti-app-5c9f4.appspot.com',
    iosBundleId: 'com.example.wayoChatapp.RunnerTests',
  );
}
