// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuQ0JZccMGBM6xVorEEzxOjUoPF93LRo',
    appId: '1:1074657064584:web:5d2ffec5a27a0dda41913d',
    messagingSenderId: '1074657064584',
    projectId: 'wayo-chat',
    authDomain: 'wayo-chat.firebaseapp.com',
    storageBucket: 'wayo-chat.appspot.com',
    measurementId: 'G-PQRKGD2MHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBycNUpozwMjHjc6FJLY7c12QjTPb-3YGQ',
    appId: '1:1074657064584:android:49d734b6e722d9f841913d',
    messagingSenderId: '1074657064584',
    projectId: 'wayo-chat',
    storageBucket: 'wayo-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi8g1bKRLVfQAcjN05IhFjPzAn25UfMN8',
    appId: '1:1074657064584:ios:dbf3bd3550ae281f41913d',
    messagingSenderId: '1074657064584',
    projectId: 'wayo-chat',
    storageBucket: 'wayo-chat.appspot.com',
    iosBundleId: 'com.example.wayoChatapp',
  );
}
